[Clean] bootstrap: 4 spaces -> 2 spaces

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -16,34 +16,34 @@ BUILD_DIR=./build # build destination
 
 function main
 {
-    local no_build=$1
+  local no_build=$1
 
-    autoreconf --force --install --warnings=all
+  autoreconf --force --install --warnings=all
+  local ret_code=$?
+  if [[ $ret_code -ne 0 ]]; then
+    exit $ret_code
+  fi
+
+
+  rm -rf "$BUILD_DIR"
+  mkdir -p "$BUILD_DIR"
+
+  pushd "$BUILD_DIR"
+  ../configure # TODO find the configure wherever the build folder is
+  local ret_code=$?
+  if [[ $ret_code -ne 0 ]]; then
+    exit $ret_code
+  fi
+
+
+  if [[ "$no_build" == "" ]]; then
+    make -j$(grep -c processor /proc/cpuinfo)
     local ret_code=$?
     if [[ $ret_code -ne 0 ]]; then
-        exit $ret_code
+      exit $ret_code
     fi
-
-
-    rm -rf "$BUILD_DIR"
-    mkdir -p "$BUILD_DIR"
-
-    pushd "$BUILD_DIR"
-        ../configure # TODO find the configure wherever the build folder is
-        local ret_code=$?
-        if [[ $ret_code -ne 0 ]]; then
-            exit $ret_code
-        fi
-
-
-        if [[ "$no_build" == "" ]]; then
-            make -j$(grep -c processor /proc/cpuinfo)
-            local ret_code=$?
-            if [[ $ret_code -ne 0 ]]; then
-                exit $ret_code
-            fi
-        fi
-    popd # "$BUILD_DIR"
+  fi
+  popd # "$BUILD_DIR"
 }
 
 
@@ -51,15 +51,15 @@ function main
 # Display the script usage
 function usage
 {
-    echo ""
-    echo "Usage:"
-    echo "  $0 [--no-build]"
-    echo ""
-    echo "Options:"
-    echo "  --no-build: configure the project only, do not run make"
-    echo ""
-    echo "War Evolved build script. Version 1.0"
-    echo ""
+  echo ""
+  echo "Usage:"
+  echo "  $0 [--no-build]"
+  echo ""
+  echo "Options:"
+  echo "  --no-build: configure the project only, do not run make"
+  echo ""
+  echo "War Evolved build script. Version 1.0"
+  echo ""
 }
 
 
@@ -67,23 +67,23 @@ function usage
 # $@: command line arguments
 function check_args
 {
-    if [[ $# -gt 1 ]]; then
-        echo "Too many arguments"
-        usage
-        exit 3
-    fi
+  if [[ $# -gt 1 ]]; then
+    echo "Too many arguments"
+    usage
+    exit 3
+  fi
 
-    # TODO: don't expect help to be at a defined position
-    if [[ "$1" == "--help" || "$1" == "-h" ]]; then
-        usage
-        exit 0
-    fi
+  # TODO: don't expect help to be at a defined position
+  if [[ "$1" == "--help" || "$1" == "-h" ]]; then
+    usage
+    exit 0
+  fi
 
-    if [[ "$1" && "$1" != "--no-build" ]]; then
-        echo "Invalid argument $1"
-        usage
-        exit 3
-    fi
+  if [[ "$1" && "$1" != "--no-build" ]]; then
+    echo "Invalid argument $1"
+    usage
+    exit 3
+  fi
 }
 
 
