[Tools] Git pre-commit hook: checking Doxygen warnings/errors

diff --git a/tools/git/hooks/pre-commit b/tools/git/hooks/pre-commit
--- a/tools/git/hooks/pre-commit
+++ b/tools/git/hooks/pre-commit
@@ -1,4 +1,11 @@
 #!/bin/sh
 
+# Doxygen returns 0 on warning
+doxygen_output="$(doxygen 2>&1)"
+if [ "$doxygen_output" != "" ]; then
+  echo "Doxygen failure(s) detected:"
+  echo "$doxygen_output"
+  exit 1
+fi
+
 tools/coding_style.sh src/
-# tools/check_headers.sh src/
